obs_info fix
NCAR/DART pull request #181
Opened 2021-03-12 22:21 UTC by nancycollins

the original program may have worked on obs kinds which do start
at 0, but these are now handling obs types which start at 1.
make all arrays and loops start at index 1.  also fix the input.nml
namelists for obs_info_nml to have better defaults.

this is related to [issue #147](https://github.com/NCAR/DART/issues/147)

(low priority.  just figuring out the simpler workflow with git.)

2021-03-12 22:33 UTC, hkershaw-brown commented
Hey Nancy, 
is this change due to the new preprocess method? Or is this has this been around since the types/kinds changeover?

2021-03-12 22:35 UTC, nancycollins commented
just broken since the types/kinds changeover.  nothing to do with the new preprocess.

2021-03-12 22:41 UTC, hkershaw-brown commented
ok cool thanks.

2021-03-17 15:04 UTC, hkershaw-brown requested changes
`print_obs_seq` is not called in this program, so the subroutine in this file is never used. 
There is a `print_obs_seq` in `obs_seq_utilities_mod.f90` that is public. That one has kinds in the variable names, not types. 

There are 10 versions of `print_obs_seq`, which I think is about 9 too many:

````
./assimilation_code/programs/obs_utils/obs_sort.f90:535:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_utils/obs_info.f90:305:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_utils/obs_data_denial.f90:314:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_utils/obs_remove_dups.f90:551:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_selection/obs_selection.f90:675:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_sequence_tool/obs_sequence_tool.f90:1149:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_keep_a_few/obs_keep_a_few.f90:303:subroutine print_obs_seq(seq_in, filename)
./assimilation_code/programs/obs_common_subset/obs_common_subset.f90:713:subroutine print_obs_seq(seq_in, filename)
./developer_tests/obs_sequence/obs_rwtest.f90:190:subroutine print_obs_seq(seq_in, filename)
./observations/obs_converters/utilities/obs_seq_utilities_mod.f90:82:subroutine print_obs_seq(seq, filename)
````

The `obs_seq_utilites_mod.f90` I don't think is used at all since it is not in any pathnames files. 
I'd like to zoom out a bit from this pull request and look at the various obs_seq_tools and whether these obs_seq programs should be using obs_seq_utitilies_mod.  Probably there is duplication of `validate_obs_seq_time`  `print_metadata` also.

2021-03-18 15:59 UTC, hkershaw-brown approved these changes
Even though the code is not being called, this pull request fixes the compiler warning, and sets sensible input.nml values for the observations/utilities.

2021-03-18 15:59 UTC, merged

2021-03-18 22:24 UTC, nancycollins commented
hey, are you impugning the time-honored technique of "copy the entire file and edit a few lines" to get my "lines of code per day" numbers up?

seriously, i'll open an issue on the pile of code in the obs_utils dir and paste your comments in.  all valid.

2021-03-18 22:55 UTC, hkershaw-brown commented
I think this is ok if you are getting paid by the line.