Fix grammar/typo in feature_request.md template.
NCAR/DART pull request #268
Opened 2021-08-08 18:40 UTC by nancycollins

fix grammar and typo in the 'Describe your preferred solution' line.

## Description:

Please provide a summary of the change and include any relevant motivation and context. 

### Fixes issue

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Please describe any tests you ran to verify your changes.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Version tag 

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

2021-08-09 15:06 UTC, hkershaw-brown commented
There are a couple of other typos/missing bits of doc hanging out.  May as well add them to this pull request and get someone who can read to review them

2021-08-10 17:54 UTC, kdraeder requested changes
One comment in obs_sequence_tool clarifying parts of an observation versus
one out of the whole set of observations.

2021-08-10 19:08 UTC, hkershaw-brown commented
> One comment in obs_sequence_tool clarifying parts of an observation versus
> one out of the whole set of observations.

done.

2021-08-10 19:23 UTC, kdraeder approved these changes

2021-08-10 20:25 UTC, merged