Upgrade Rttov13 + WRF changes
NCAR/DART pull request #367
Opened 2022-06-29 11:32 UTC by lkugler

## Description:

- Mostly changes to allow the use of RTTOV13
- WRF temperature variable changed from T to THM in WRF's model_mod
- Allow interpolate to access the uppermost level of the WRF state.

### Fixes issue

- #366 
- #365 
- RTTOV12->13 upgrade has no issue

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue): #365 
- [x] New feature (non-breaking change which adds functionality): RTTOV upgrade
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected): RTTOV-SCATT is not tested! Code missing! 
- [ ] Documentation update

### Documentation changes needed?

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### Tests

- rttov13 changes: comparison to my own script using the python interface of RTTOV
- WRF allow accessing the top level of the WRF state in interpolate: ./perfect_model_obs gave the expected results
- cange to THM as type_t variable: ./perfect_model_obs did not crash

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Version tag 

## Testing Datasets

- [x] Dataset needed for testing has been provided: 
wrfout state, expected output in netcdf format, obs_seq.in

2022-06-29 14:06 UTC, lkugler commented
### Before-image
![Comparison before](https://user-images.githubusercontent.com/29361544/176202803-36127c0e-6ffc-4aaf-af49-ab4161a750ee.png)
### After-image VIS
![Comparison after VIS](https://user-images.githubusercontent.com/29361544/176456828-1fc36bac-ff51-4b8b-9825-e9df8c65c667.png)

### After-image WV
![Comparison after WV](https://user-images.githubusercontent.com/29361544/176448515-126bf74a-c3f9-4ea0-a6e1-50a086747829.png)

2022-06-29 15:42 UTC, nancycollins commented
by the way, really nice catch on the inverted column(s).

2022-06-30 01:06 UTC, hkershaw-brown requested changes
Hi Lukas, 

This is great work to get the rttov13 interface up and running. 

For the  obs_def_rttov13_mod.f90, at the moment git is interpreting this as a `git mv` so 
obs_def_rttov_mod.f90 no longer exists in this branch.

Because we have people using rttov 12, for this pull request I'd like to have

obs_def_rttov_mod.f90
obs_def_rttov13_mod.f90 

I think this makes clearer if we do depreciate rttov12 in a future release.

The mkmf.template can have a VERSION variable so we do not need two mkmf.template.rttov for each compiler:

e.g.
```
RTTOV_VERSION = 13

RTLIBS = -lrttov$(RTTOV_VERSION)_wrapper
```

I can go ahead and make these two changes if you are comfortable with me editing your branch. 

Cheers,
Helen

2022-06-30 01:07 UTC, hkershaw-brown commented on models/wrf/model_mod.f90
> +default_table(:,row) = (/ 'THM                       ', &
note, T vs THM is a wrf v3 to v4 issue. T is prognostic in v4.

Inside WRF, use_theta_m=0 for T= THM

2022-06-30 15:26 UTC, lkugler commented
We can also remove the commit related to the levels (https://github.com/NCAR/DART/pull/367/commits/25efb6c8ac49e5322300e0a5dd2244dc61e157bb) from this PR?! Since its a separate thing.
Following the discussion in #366

2022-08-02 00:10 UTC, hkershaw-brown commented
I'm splitting the WRF and RTTOV parts of this pull request.

The WRF changes are on https://github.com/NCAR/DART/tree/wrf-thm

2022-08-02 19:54 UTC, hkershaw-brown approved these changes
Approved.

Splitting the WRF updates to a separate pull request to support wrf3 and wrf4 users.

2022-08-02 20:00 UTC, merged