Bug xtime
NCAR/DART pull request #414
Opened 2022-10-13 20:34 UTC by achauphan

## Description:

Fixes #411 

### Fixes issue

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.

### Tests
Please describe any tests you ran to verify your changes.

## Checklist for merging

- [ ] Updated changelog entry
- [x] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

2022-10-13 21:02 UTC, nancycollins commented
hi anderson,

you don't want to add the log files to the repo, even though they're interesting.  you also can't alter the documentation in the readme.rst because that's showing what the mpss init files look like and it's going to be 64 when someone dumps the file. 
 the mpas_init file comes from the scientist running mpas, so you can't change the string length in it.  that's under the model's control. 

if that dart write time routine is creating a variable from scratch, i think it has to stay length 64 because mpas may be expecting that to be the case when it reads in the file.   i think you may need to set the string time with the get_time() routine and then set the 20th character to null (using char(0) ) to terminate the string.  in fortran the valid parts of the string have a known length as well as a max length, but in C the string is terminated by a null character.  if you have 19 good characters and a 20th null char that may fix it.  or you may need to initialize the entire string to char(0) first and then call the get_time() routine.  see if that works?

2022-10-13 21:55 UTC, achauphan commented
Hi Nancy, thanks for pointing out those log files I had included. 
Your recommended approach to fixing this issue does make more sense to avoid conflicting expectations in the defined lengths for until the timestring is populated. I'll give it a go.

2022-10-13 22:26 UTC, nancycollins commented
helen pointed out to me that using the fortran "trim()" intrinsic on the string being passed to nc_put_variable on line 3081 might be all it needs.  instead of passing **timestring** as the third arg, try passing **trim(timestring)** instead and see if the fortran routines take care of it themselves.

2022-10-24 21:01 UTC, hkershaw-brown requested changes
Fix looks good. 

The file `models/mpas_atm/dart_log_fail.out` needs removing from this pull request.

2022-10-24 22:06 UTC, hkershaw-brown commented on models/mpas_atm/model_mod.f90
> +character(len=64) :: timestring = ''
Note to check before we merge this. Initializing in the declaration is an implicit save in Fortran, so `timestring` is only initialed on the first call to `write_model_time_restart`. We may want to change the initialization to be separate:

```suggestion
character(len=64) :: timestring
timestring = ''
```

2022-10-28 15:38 UTC, hkershaw-brown approved these changes
Great work on this bug fix Anderson. 

We'll bundle release this with #418

2022-11-03 18:27 UTC, merged