Updating mpi_utilities_mod to use the mpi_f08 module
NCAR/DART pull request #552
Opened 2023-09-28 18:18 UTC by mjs2369

## Description:

Errors from mpi_utilities_mod are produced when cray-mpich and gfortran use f77 bindings with `use mpi`

The f08 mpi module `use mpi_f08` follows the fortran standard.
mpi_utilites_mod has been updated to use the mpi_f08 module with mpi_f08 bindings. 

This fixes the issues with mpich and gfortran 10+

The following items were mentioned in the corresponding issues, but will not be addressed in the PR and will be a part of a larger refactor of our MPI code:
- Updating mpi_utilities_mod to MPI3 - MPI_INTEGER_KIND, MPI_COUNT_KIND 
- Removal of the cray pointer window
- maybe using fortran intrinsics for executing other programs so we don't have to use fixsystem

### Fixes issue
Fixes #261 #551 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Ran quickbuild.sh using the gfortran compiler with full debugging flags on Derecho; executed filter
Repeated this process for the Intel and cce compilers to ensure these changes didn't affect the other compilers' ability to compile and run.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [x] No dataset needed

2023-09-28 18:28 UTC, hkershaw-brown commented
@mjs2369 Thanks Marlee! 
I'm going to live dangerously and amend the commit message on this to describe the changes.

2023-09-29 14:02 UTC, hkershaw-brown requested changes
Does not compile on Cheyenne with mpt

```
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.o: in function `mpi_utilities_mod_mp_finalize_mpi_utilities_':
mpi_utilities_mod.f90:(.text+0x135): undefined reference to `mpi_barrier_f08_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.f90:(.text+0x1d9): undefined reference to `sgi_mpi_f08_comm_world'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.f90:(.text+0x1de): undefined reference to `mpi_f08_types_mp_mpi_comm_op_ne_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.f90:(.text+0x1ec): undefined reference to `sgi_mpi_f08_comm_world'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.f90:(.text+0x2a7): undefined reference to `mpi_finalize_f08_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.f90:(.text+0x3a7): undefined reference to `mpi_comm_free_f08_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: mpi_utilities_mod.o: in function `mpi_utilities_mod_mp_task_sync_':
```

```
module -t list
ncarenv/1.3
intel/19.1.1
ncarcompilers/0.5.0
netcdf/4.8.1
mpt/2.25
```

2023-09-29 14:28 UTC, hkershaw-brown commented
Cheyenne: for mpt use mpif08

```
MPIFC = mpif08
MPILD = mpif08
FC = ifort
LD = ifort
```

2023-09-29 14:34 UTC, hkershaw-brown commented
```
/glade/scratch/hkershaw/DART/pull_requests/pull_552/DART.intel/assimilation_code/modules/utilities/mpi_utilities_mod.f90(1989): warning #8100: The actual argument is an array section or assumed-shape array, corresponding dummy argument that has either the VOLATILE or ASYNCHRONOUS attribute shall be an assumed-shape array.   [X]
call mpi_get(x, num_rows, datasize, owner, target_disp, num_rows, datasize, window, errcode)
-------------^
```

2023-09-29 14:34 UTC, nancycollins reviewed
a couple small suggestions, but otherwise looks ok to me.

2023-09-29 14:34 UTC, nancycollins commented on assimilation_code/modules/utilities/mpi_utilities_mod.f90
> +type(MPI_Comm) :: my_local_comm  ! duplicate communicator private to this file
is there a way to give these an initial value that is not legal?  it would help to catch if they ever got used before being initialized.

2023-09-29 14:34 UTC, nancycollins commented on assimilation_code/modules/utilities/mpi_utilities_mod.f90
> +use mpi_f08
maybe add a comment before this line for the user, saying if you don't have the 2008 version of mpi available, try 'use mpi' instead?

2023-09-29 14:38 UTC, nancycollins commented
i forgot to mention that there are test programs in the developer_test directory that are very simple standalone MPI and NetCDF programs that i used to point people having problems to.  they aren't as complex as compiling any of the main dart code - they're standalone and help people who have system configuration problems.  maybe have these 'use mpi_f08' if they don't still compile, and have some comments about 'use mpi' vs 'use mpi_f08' for users trying to track down problems.
they're in developer_tests/mpi_utilities/tests

2023-09-29 15:21 UTC, hkershaw-brown commented
Derecho nvfotran ftn:

```
NVFORTRAN-F-0004-Unable to open MODULE file mpi_f08.mod (/glade/derecho/scratch/hkershaw/DART/pull_reqeuests/pull_552/DART.nvhpc/assimilation_code/modules/utilities/mpi_utilities_mod.f90: 53)
NVFORTRAN/x86-64 Linux 23.1-0: compilation aborted
```
 Derecho nvfortran mpif08
```
mpif08 -O -Mbackslash -Kieee -I/glade/u/apps/derecho/23.06/spack/opt/spack/netcdf/4.9.2/nvhpc/23.1/qwj3/include  -c	/glade/derecho/scratch/hkershaw/DART/pull_reqeuests/pull_552/DART.nvhpc/assimilation_code/modules/utilities/types_mod.f90
NCAR_ERROR: wrapper cannot locate path to mpif08
```

```
ls /glade/u/apps/derecho/23.06/spack/opt/spack/ncarcompilers/1.0.0/nvhpc/23.1/rqst/bin/mpi/mpif08
/glade/u/apps/derecho/23.06/spack/opt/spack/ncarcompilers/1.0.0/nvhpc/23.1/rqst/bin/mpi/mpif08
$ mpif08
NCAR_ERROR: wrapper cannot locate path to mpif08
```

2023-09-29 16:31 UTC, hkershaw-brown commented
@mjs2369 I'm going to close this pull request.  The fix is good for compiler + mpi combos that have an mpi_f08.mod
but we still have a lot of compiler mpi combinations that don't support mpif08.

I'm thinking maybe a mpif08 option is the way to go, so you can build with the f08 or f90 bindings for mpi.
`quickbuild.sh mpif08`

2023-09-29 16:31 UTC, closed without merging