Create citation.cff for DART
NCAR/DART pull request #658
Opened 2024-03-21 17:54 UTC by ann-norcio

## Description:
Add a citation.cff file to help users correctly cite DART software. Creates a link to cite the repository on the landing page sidebar.

### Fixes issue
https://github.com/NCAR/DART/issues/643

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Followed citation file formatting on [Github Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [X] No dataset needed

2024-03-21 18:01 UTC, mgharamti commented
Nice!

2024-03-21 18:45 UTC, hkershaw-brown requested changes
Looks like there is something something funky in the .cff
![Screen Shot 2024-03-21 at 2 44 32 PM](https://github.com/NCAR/DART/assets/20047007/3deca4eb-9663-42ec-a1eb-ea6ea546d0dd)

2024-03-21 19:30 UTC, ann-norcio commented
Changed **date-released** format to "YYY-MM-DD" and **names** to **name**. Should work as expected now.
<img width="1399" alt="cff" src="https://github.com/NCAR/DART/assets/142816397/de0386b9-c879-43cb-92ac-e7c87cc8e623">

2024-03-22 14:53 UTC, hkershaw-brown reviewed
I think this looks good Ann (one change for the doi entry: APA puts the http://doi.org in for you and Bibtex recommends the 10.XXXXX only).

I think if @moha is ok with how the citation looks it is good to go.

2024-03-22 14:53 UTC, hkershaw-brown commented on CITATION.cff
> +doi: "http://doi.org/10.5065/D6WQ0202"
```suggestion
doi: "10.5065/D6WQ0202"
```

The doi is coming out as 
UCAR/NCAR/CISL/DAReS. (2024). The Data Assimilation Research Testbed (Version X.Y.Z) [Computer software]. https://doi.org/http://doi.org/10.5065/D6WQ0202

on the APA citation.

2024-03-22 14:54 UTC, hkershaw-brown commented
> mgharamti

oops @ the wrong moha @mgharamti

2024-03-22 14:57 UTC, mgharamti commented
This looks good to me. Thanks Ann and Helen!

2024-03-22 16:23 UTC, hkershaw-brown approved these changes

2024-03-27 22:59 UTC, merged