Check list of state variables for required ones
NCAR/DART pull request #776
Opened 2024-11-14 18:54 UTC by kdraeder

## Description:

User's can specify in model_nml which variables should be in the state vector.
They are currently free to leave out variables that are required for some calculations.
Filter writes no useful message about this problem when it fails, which results in a long debugging process.
This fix adds a function call after model_nml has been read and parsed to check whether required variables are in the state, and exit with a helpful message when one is missing.  
The lists of required variables are different for cam-fv and cam-se, and may change in the future.

### Fixes issue
#662

### Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
I ran both cam-fv and cam-se using model_nml:state_variables which contained

1. all required variables
2. all except for PS
3. all except for CLDICE (cam-se only; dry mass calculation)

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

2024-12-03 15:42 UTC, hkershaw-brown requested changes
Hi Kevin,

Functionally the code looks to be doing the checks for the required state variables. At the moment you code seems a bit over complicated, I've put some comments on simplifying it. 

You have some debugging statements, that will only print on task 0. I'd advocated for not putting these debugging statements in (see comment on the ~3 places these debug statements were added)

The change in value for the istatus (16 vs 26) - it would be good to know what this change was for.

Do you have a cam-se case I can grab on Derecho that I can add to our test cases? If not I can spin one up. 

Cheers,
Helen

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +   endif
whats the goal of adding this message? And does it need to be in this pull request?
E_MSG means only task 0 will print this. If other tasks have a non-zero istatus you won't get a message.

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +         endif
same message comment: do you need to have task 0 print this?

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +   endif
same message comment: do you need to have task 0 print this?

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +         endif
same message comment: do you need to have task 0 print this?
You could set a conditional debug in a debugger to catch these on any task if you need to debug.

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +                 * sum_dry_mix_ratio(k, n)
Is this a change to the calculation? Or are you just wrapping the line.
If it is just a line wrap change, I would not do this change in this pull request.

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +! and 27 if unable to find values at upper level.
What is the significance of 26 vs 16? 27 vs 17? Did these clash with other my_status values?

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +
What is this comment referring to?  
It looks like some notes from the previous commit. I'd remove this or if it is a necessary comment, put the comment by the code it is describing.

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +data var_names /'PS', 'Q', 'CLDLIQ', 'CLDICE', 6*''/
functionally this looks to be doing what is should, but it seems a little over complicated. 

Why do you have 10 var_names, but only 4 names, and 6 blank strings?

Why is PS in the var_names array? 
You could check for PS (always required), then loop though your sometimes required variables. 
That way 
```
i = 1
i = i+1
if (dry_mass_vertical_coordinate .and. precise_dry_mass_get_close) then
do while (var_names(i) .ne. '')
  i = i + 1
enddo
endif
```
becomes
```
check for PS
if (dry_mass_vertical_coordinate .and. precise_dry_mass_get_close) then
  do i = 1, 3
  enddo
endif
```

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.nml
> +                      'PS',    'QTY_SURFACE_PRESSURE',    'NA', 'NA', 'UPDATE'
good catch putting these in model_mod.nml

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +call verify_state_var_list
this is a nitpick, but I think your routine name is clear enough that you don't need this comment.

```
! this routine does stuff
call do_stuff
```

2024-12-03 15:42 UTC, hkershaw-brown commented on models/cam-fv/model_mod.f90
> +data var_names /'PS', 9*''/
I don't think you need a data statement & and i variable here
You only have 'PS' so you could call 

`varid = get_varid_from_varname(domain_id, 'PS')`

2024-12-18 14:39 UTC, hkershaw-brown commented
Hi Kevin, just checking in on this cam-se pull request and the review comments. Is your plan to work on this?

2024-12-18 14:44 UTC, kdraeder commented
I do plan to finish this after reviewing 740 for Jeff.
I lost momentum on it during the AGU scramble.
Thanks for all of your comments!

2025-01-03 16:41 UTC, kdraeder commented on models/cam-se/model_mod.f90
> +         endif
Thanks for the debugger suggestion.  Now I understand why people prefer to remove most debugging code; it's apparently easy to install temporarily when using debuggers.  I use debuggers so seldom that I need to climb a big learning curve every time, so I end up opting for adding debugging code directly.  So it looks like these should be removed, even though they would have saved me time.

2025-01-03 16:51 UTC, kdraeder commented
The change of istatus values from {16,17} to {26,27} in get_se_four_nonstate_values was useful to me because {16,17} are already used in get_se_four_state_values, so I couldn't see which subroutine was returning a non-0 value.  It doesn't seem to break anything or add code, so I left it in to save time in the future.

2025-01-03 16:58 UTC, kdraeder commented on models/cam-se/model_mod.f90
> +                 * sum_dry_mix_ratio(k, n)
No calculation change - just a reformatting so that I could see the calculation more clearly.
It seems easy to see that, so I didn't comment about it in the commit message.  Should I have?
Or is this a question of sticking strictly to the topic of the PR?
Do we ever do PRs that are focused on making the code more readable, fixing typos,...?

2025-01-03 17:00 UTC, kdraeder commented on models/cam-se/model_mod.f90
> +
This was just useful during the debugging and fixing process.  I've removed it.

2025-01-03 17:19 UTC, kdraeder commented on models/cam-se/model_mod.f90
> +data var_names /'PS', 'Q', 'CLDLIQ', 'CLDICE', 6*''/
My intent was to write generic and flexible code; more fields may need to be added to var_names in the future and it would be nice if the only required change is to var_names, and not finding where var_names is dimensioned and then used, and changing the sizes there.  Although size(var_names) coud be used for the loop.
A more comprehensive fix in the future might involve var_names being passed in, so the code I wrote would be more easily adapted to that.
But if the priority is short code to solve the immediate problem, then I'll do that.

2025-01-03 17:23 UTC, kdraeder commented on models/cam-fv/model_mod.f90
> +data var_names /'PS', 9*''/
I was making it consistent with the cam-se version to make comparisons easier, and to keep the flexibility for adding fields to the list in the future.
If that's misguided I'll simplify the cam-fv version.

2025-01-06 13:31 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +                 * sum_dry_mix_ratio(k, n)
It is  this a question of sticking strictly to the topic of the PR.  We have very limited test coverage, hand-run tests, and limited reviewers.

2025-01-14 17:55 UTC, hkershaw-brown commented
Hi Kevin, are you planning on working on this this week, if not I'll go ahead and make the changes unless you have a burning desire to do the changes yourself.

2025-01-21 20:17 UTC, hkershaw-brown commented
> Hi Kevin, are you planning on working on this this week, if not I'll go ahead and make the changes unless you have a burning desire to do the changes yourself.

Hi just pinging again on this, is this something that you are working on?, if not I'll go ahead and make the changes. Cheers,
Helen

2025-01-28 20:42 UTC, kdraeder commented
@hkershaw-brown  I've made the 'resolved' changes in my clone.  
There are a couple open questions above about which additional changes I should make, 
so when we've answered  these questions I'll make the remaining recommended changes 
and push the commit.

2025-01-28 20:51 UTC, hkershaw-brown commented
> @hkershaw-brown I've made the 'resolved' changes in my clone.

Go ahead and commit and push the changes for the 'resolved', otherwise it is not resolved in the repo. You can put other changes in another commit.

2025-01-28 22:19 UTC, hkershaw-brown commented on models/cam-fv/model_mod.f90
> +data var_names /'PS', 9*''/
yup simplify the cam-fv version

2025-01-28 22:36 UTC, kdraeder commented on models/cam-se/model_mod.f90
> +data var_names /'PS', 'Q', 'CLDLIQ', 'CLDICE', 6*''/
@hkershaw-brown  do you want any changes here, or is my motivation convincing?

2025-01-28 23:28 UTC, hkershaw-brown commented
Oh simplify for sure!

On Tuesday, January 28, 2025, kdraeder ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In models/cam-se/model_mod.f90
> <https://github.com/NCAR/DART/pull/776#discussion_r1932957042>:
>
> > @@ -3319,6 +3353,43 @@ end subroutine solve_quadratic
>
>  !-----------------------------------------------------------------------
>
> +subroutine verify_state_var_list
> +
> +! No return is needed.  A diagnostic statement is printed before a potential failure
> +! of get_varid_from_varname.  Success means carry on.
> +
> +! There could be more moisture variables than the traditional 3.
> +character(len=32), dimension(10) :: var_names
> +integer:: i, varid
> +
> +data var_names /'PS', 'Q', 'CLDLIQ', 'CLDICE', 6*''/
>
> @hkershaw-brown <https://github.com/hkershaw-brown> do you want any
> changes here, or is my motivation convincing?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/DART/pull/776#discussion_r1932957042>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEY6JH6BLNQXRICQCZTVB3D2NAA7HAVCNFSM6AAAAABRZSPTOGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNZZGU3DOOJUGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-29 13:44 UTC, hkershaw-brown commented on models/cam-se/model_mod.f90
> +data var_names /'PS', 'Q', 'CLDLIQ', 'CLDICE', 6*''/
Oh simplify for sure!

2025-01-31 18:40 UTC, hkershaw-brown approved these changes
Nice! thanks Kevin 
Approved!

2025-02-03 14:01 UTC, merged